apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome To 2024 By Volvo</h1>
    </br>
    <h1>Hi! This is a Interview Demo  </h1>
    </html
